[build]
  base = "public"
  command = "CI=false npm run build"
  publish = "public/build"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.environment]
  NODE_VERSION = "18"
  CI = "false"